/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.log.in;
import javax.swing.JOptionPane;

/**
 *
 * @author haruaiah
 */
public class ordersystem extends javax.swing.JFrame {

    /**
     * Creates new form ordersystem
     */
    public ordersystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        Latiao = new javax.swing.JCheckBox();
        Hawflakes = new javax.swing.JCheckBox();
        Woonut = new javax.swing.JCheckBox();
        jTextField2 = new javax.swing.JTextField();
        latiao_quan = new javax.swing.JSpinner();
        hawflakes_quan = new javax.swing.JSpinner();
        woonut_quan = new javax.swing.JSpinner();
        qty1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        total_order = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        cash = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        co = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        Dutch = new javax.swing.JCheckBox();
        Mogumogu = new javax.swing.JCheckBox();
        Soybean = new javax.swing.JCheckBox();
        dutch_quan = new javax.swing.JSpinner();
        mogu_quan = new javax.swing.JSpinner();
        soybean_quan = new javax.swing.JSpinner();
        qty2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Krungthep", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("FAECHI STORE");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 50));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 97, 153));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Latiao.setBackground(new java.awt.Color(102, 255, 204));
        Latiao.setFont(new java.awt.Font("Kannada MN", 1, 13)); // NOI18N
        Latiao.setText("LATIAO");
        Latiao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel1.add(Latiao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 30));

        Hawflakes.setBackground(new java.awt.Color(102, 255, 204));
        Hawflakes.setFont(new java.awt.Font("Kannada MN", 1, 13)); // NOI18N
        Hawflakes.setText("HAW FLAKES");
        panel1.add(Hawflakes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 30));

        Woonut.setBackground(new java.awt.Color(102, 255, 204));
        Woonut.setFont(new java.awt.Font("Kannada Sangam MN", 1, 13)); // NOI18N
        Woonut.setText("WOONUT");
        panel1.add(Woonut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, -1));

        jTextField2.setBackground(new java.awt.Color(138, 207, 248));
        jTextField2.setFont(new java.awt.Font("Krungthep", 1, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("SNACKS");
        jTextField2.setBorder(new javax.swing.border.MatteBorder(null));
        panel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        latiao_quan.setFont(new java.awt.Font("Krungthep", 1, 13)); // NOI18N
        panel1.add(latiao_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 60, 90, 30));

        hawflakes_quan.setFont(new java.awt.Font("Krungthep", 1, 13)); // NOI18N
        panel1.add(hawflakes_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 100, 90, 30));

        woonut_quan.setFont(new java.awt.Font("Krungthep", 1, 13)); // NOI18N
        panel1.add(woonut_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 140, 90, 30));

        qty1.setBackground(new java.awt.Color(138, 207, 248));
        qty1.setFont(new java.awt.Font("Krungthep", 1, 13)); // NOI18N
        qty1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qty1.setText("QTY");
        qty1.setBorder(new javax.swing.border.MatteBorder(null));
        panel1.add(qty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 10, 90, 30));

        jPanel2.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 180));

        jPanel3.setBackground(new java.awt.Color(6, 97, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total_order.setBackground(new java.awt.Color(102, 255, 204));
        total_order.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        total_order.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_order.setText("TOTAL ORDER: ");
        jPanel3.add(total_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        amount.setFont(new java.awt.Font("Krungthep", 1, 13)); // NOI18N
        jPanel3.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 90, -1));

        cash.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        cash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cash.setText("CASH AMOUNT:");
        jPanel3.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jButton1.setBackground(new java.awt.Color(255, 212, 68));
        jButton1.setFont(new java.awt.Font("Krungthep", 1, 13)); // NOI18N
        jButton1.setText("PAY");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 130, 240, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 280, 180));

        co.setBackground(new java.awt.Color(255, 212, 68));
        co.setFont(new java.awt.Font("Krungthep", 1, 18)); // NOI18N
        co.setText("CONFIRM ORDER");
        co.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        co.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coActionPerformed(evt);
            }
        });
        jPanel2.add(co, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 97, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setBackground(new java.awt.Color(138, 207, 248));
        jTextField3.setFont(new java.awt.Font("Krungthep", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("DRINKS");
        jTextField3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 30));

        Dutch.setBackground(new java.awt.Color(102, 255, 204));
        Dutch.setFont(new java.awt.Font("Kannada Sangam MN", 1, 13)); // NOI18N
        Dutch.setText("DUTCH MILL");
        jPanel1.add(Dutch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 30));

        Mogumogu.setBackground(new java.awt.Color(102, 255, 204));
        Mogumogu.setFont(new java.awt.Font("Kannada Sangam MN", 1, 13)); // NOI18N
        Mogumogu.setText("MOGU MOGU");
        jPanel1.add(Mogumogu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 160, 30));

        Soybean.setBackground(new java.awt.Color(102, 255, 204));
        Soybean.setFont(new java.awt.Font("Kannada Sangam MN", 1, 13)); // NOI18N
        Soybean.setText("SOYBEAN MILK");
        jPanel1.add(Soybean, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, 30));

        dutch_quan.setFont(new java.awt.Font("Krungthep", 1, 13)); // NOI18N
        jPanel1.add(dutch_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 60, 90, 30));

        mogu_quan.setFont(new java.awt.Font("Krungthep", 1, 13)); // NOI18N
        jPanel1.add(mogu_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 100, 90, 30));

        soybean_quan.setFont(new java.awt.Font("Krungthep", 1, 13)); // NOI18N
        jPanel1.add(soybean_quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 140, 90, 30));

        qty2.setBackground(new java.awt.Color(138, 207, 248));
        qty2.setFont(new java.awt.Font("Krungthep", 1, 13)); // NOI18N
        qty2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qty2.setText("QTY");
        qty2.setBorder(new javax.swing.border.MatteBorder(null));
        qty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty2ActionPerformed(evt);
            }
        });
        jPanel1.add(qty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 10, 90, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 280, 180));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String list = "";
    private int total = 0;
    private void resetOrder(){
        list = "";
        total = 0;
    }
    private void processOrder(){
        coActionPerformed(null);
    }
    private void anotherOrder(){
        int choice = JOptionPane.showConfirmDialog(null, "Would you like to make another order?", "Another Order", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION){
            list = "";
            total = 0;
            amount.setText("");
            
            Latiao.setSelected(false);
            Hawflakes.setSelected(false);
            Woonut.setSelected(false);
            Dutch.setSelected(false);
            Mogumogu.setSelected(false);
            Soybean.setSelected(false);
            
            latiao_quan.setValue(0);
            hawflakes_quan.setValue(0);
            woonut_quan.setValue(0);
            dutch_quan.setValue(0);
            mogu_quan.setValue(0);
            soybean_quan.setValue(0);
            
            processOrder();
        }else{
            JOptionPane.showMessageDialog(null, "Thank you for your order");
            amount.setText("");
            
            Latiao.setSelected(false);
            Hawflakes.setSelected(false);
            Woonut.setSelected(false);
            Dutch.setSelected(false);
            Mogumogu.setSelected(false);
            Soybean.setSelected(false);
            
            latiao_quan.setValue(0);
            hawflakes_quan.setValue(0);
            woonut_quan.setValue(0);
            dutch_quan.setValue(0);
            mogu_quan.setValue(0);
            soybean_quan.setValue(0);
        }
    }
    
    private void coActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coActionPerformed
        total = 0;
        list = "";
        
        while(true){
            
            if(!Latiao.isSelected()){
            int quantity = (int) latiao_quan.getValue();
            if(quantity != 0){
                latiao_quan.setValue(0);
                resetOrder();
                continue;
            }
        }else if(Latiao.isSelected()){
            if((int) latiao_quan.getValue() > 0){
                int quantity = (int) latiao_quan.getValue();
                int price = 25;
                int subtotal = quantity * price;
                total += subtotal;
                if(quantity > 0){
                list += "Latiao x" + quantity + " - " + "P" + subtotal + "\n";
                }
            }else{
                JOptionPane.showMessageDialog(null,"please enter a QTY for Latiao");
                latiao_quan.setValue(0);
                return;
            }
        }
        if(!Hawflakes.isSelected()){
            int quantity = (int) hawflakes_quan.getValue();
            if(quantity != 0){
                hawflakes_quan.setValue(0);
                resetOrder();
                continue;
            }
        }else if(Hawflakes.isSelected()){
            if((int) hawflakes_quan.getValue() > 0){
                int quantity = (int) hawflakes_quan.getValue();
                int price = 30;
                int subtotal = quantity * price;
                total += subtotal;
                if(quantity > 0){
                list += "Haw Flakes x" + quantity + " - " + "P" + subtotal + "\n";
                }
            }else{
                JOptionPane.showMessageDialog(null,"please enter a QTY for Haw Flakes");
                hawflakes_quan.setValue(0);
                return;
            }
        }
        if(!Woonut.isSelected()){
            int quantity = (int) woonut_quan.getValue();
            if(quantity != 0){
                woonut_quan.setValue(0);
                resetOrder();
                continue;
            }
        }else if(Woonut.isSelected()){
            if ((int) woonut_quan.getValue() > 0) {
                int quantity = (int) woonut_quan.getValue();
                int price = 15;
                int subtotal = quantity * price;
                total += subtotal;
                    
                if(quantity > 0){
                    list += "WooNut x" + quantity + " - " + "P" + subtotal + "\n";
                }
            }else{
                JOptionPane.showMessageDialog(null,"please enter a QTY for Woonut");
                woonut_quan.setValue(0);
                return;
            }
        }
        
        if(!Dutch.isSelected()){
            int quantity = (int) dutch_quan.getValue();
            if(quantity != 0){
                dutch_quan.setValue(0);
                resetOrder();
                continue;
            }
        }else if(Dutch.isSelected()){
            if((int) dutch_quan.getValue() > 0){
                int quantity = (int) dutch_quan.getValue();
                int price = 35;
                int subtotal = quantity * price;
                total += subtotal;    
                if(quantity > 0){
                    list += "Dutch Mill x" + quantity + " - " + "P" + subtotal + "\n";
                }
            }else{
                JOptionPane.showMessageDialog(null,"please enter a QTY for Dutch Mill");
                dutch_quan.setValue(0);
                return;
            }
        }
        
        if(!Mogumogu.isSelected()){
            int quantity = (int) mogu_quan.getValue();
            if(quantity != 0){
                mogu_quan.setValue(0);
                resetOrder();
                continue;
            }
        }else if(Mogumogu.isSelected()){
            if((int) mogu_quan.getValue() > 0){
                int quantity = (int) mogu_quan.getValue();
                int price = 25;
                int subtotal = quantity * price;
                total += subtotal;    
                if(quantity > 0){
                    list += "Mogumogu x" + quantity + " - " + "P" + subtotal + "\n";
                }
            }else{
                JOptionPane.showMessageDialog(null,"please enter a QTY for Mogu-mogu");
                mogu_quan.setValue(0);
                return;
            }
        }
        
        if(!Soybean.isSelected()){
            int quantity = (int) soybean_quan.getValue();
            if(quantity != 0){
                soybean_quan.setValue(0);
                resetOrder();
                continue;
            }
        }else if(Soybean.isSelected()){
            if((int) soybean_quan.getValue() > 0){
                int quantity = (int) soybean_quan.getValue();
                int price = 20;
                int subtotal = quantity * price;
                total += subtotal;    
                if(quantity > 0){
                    list += "Soybean x" + quantity + " - " + "P" + subtotal + "\n";
                }
            }else{
                JOptionPane.showMessageDialog(null,"please enter a QTY for Soybean Milk");
                soybean_quan.setValue(0);
                return;
            }
        }
        
        
        int confirm = JOptionPane.showConfirmDialog(null,"Your Current Order \n"+list,"",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            break;
        }else if(confirm == JOptionPane.NO_OPTION){
            return;
        }
        }
        total_order.setText("TOTAL ORDER: " + total);
        
    }//GEN-LAST:event_coActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int pay = Integer.parseInt(amount.getText());
        if(pay >= total){
            int change = pay - total;
            String mess ="Reciept\n----------------------\n" +  list + "\n----------------------" + String.format("\nTotal:          P%,d", total) + String.format("\nAmount Paid:    P%,d", pay) + String.format("\nChange:         P%,d", change);
            
            JOptionPane.showMessageDialog(null,mess);
        }else{
            JOptionPane.showMessageDialog(null,"Please Enter A sufficient amount");
            amount.setText("");
        }
        
        anotherOrder();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void qty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ordersystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ordersystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ordersystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ordersystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ordersystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Dutch;
    private javax.swing.JCheckBox Hawflakes;
    private javax.swing.JCheckBox Latiao;
    private javax.swing.JCheckBox Mogumogu;
    private javax.swing.JCheckBox Soybean;
    private javax.swing.JCheckBox Woonut;
    private javax.swing.JTextField amount;
    private javax.swing.JLabel cash;
    private javax.swing.JButton co;
    private javax.swing.JSpinner dutch_quan;
    private javax.swing.JSpinner hawflakes_quan;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JSpinner latiao_quan;
    private javax.swing.JSpinner mogu_quan;
    private javax.swing.JPanel panel1;
    private javax.swing.JTextField qty1;
    private javax.swing.JTextField qty2;
    private javax.swing.JSpinner soybean_quan;
    private javax.swing.JLabel total_order;
    private javax.swing.JSpinner woonut_quan;
    // End of variables declaration//GEN-END:variables
}
