/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.log.in;

import javax.swing.JOptionPane;
/**
 *
 * @author CL2-PC
 */
public class PRELIM_EXAM extends javax.swing.JFrame {
        int p1Health = 5;
        int p2Health = 5;
    /**
     * Creates new form PRELIM_EXAM
     */
    public PRELIM_EXAM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        p1txt = new javax.swing.JTextField();
        p2txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("[1] ROCK");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setBackground(new java.awt.Color(0, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("[1] ROCK");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel5.setText("[2] PAPER");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("[3] SCISSOR");

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("PLAYER 1:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setText("PLAYER 2:");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("FIGHT!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1txt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(p2txt))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(p1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(p2txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int p1 = Integer.parseInt(p1txt.getText());
        int p2 = Integer.parseInt(p2txt.getText());

        if(p1 == 1 && p2 == 1)
        {
            JOptionPane.showMessageDialog(rootPane,"DRAW","RPS" ,JOptionPane.ERROR_MESSAGE);
        }
        else if(p1 == 1 && p2 == 2)
        {   
            p1Health--; JOptionPane.showMessageDialog(rootPane,"Player 2 Wins\n Player 1 Health: " + p1Health,"RPS" ,JOptionPane.CLOSED_OPTION);
        }
        else if(p1 == 1 && p2 == 3)
        {
            p2Health--;
            JOptionPane.showMessageDialog(rootPane,"Player 1 Wins\n Player 2 Health: " + p2Health,"RPS" ,JOptionPane.CLOSED_OPTION);
        }
        if(p1 == 2 && p2 == 2)
        {
            JOptionPane.showMessageDialog(rootPane,"DRAW","RPS" ,JOptionPane.ERROR_MESSAGE);
        }
        else if(p1 == 2 && p2 == 3)
        {
            p1Health--;
            JOptionPane.showMessageDialog(rootPane,"Player 2 Wins\n Player 1 Health: " + p1Health,"RPS" ,JOptionPane.CLOSED_OPTION);
        }
        else if(p1 == 2 && p2 == 1)
        {
            p2Health--;
            JOptionPane.showMessageDialog(rootPane,"Player 1 Wins\n Player 2 Health:" + p2Health,"RPS" ,JOptionPane.CLOSED_OPTION);
        }
        if(p1 == 3 && p2 == 3)
        {
            JOptionPane.showMessageDialog(rootPane,"DRAW","RPS" ,JOptionPane.ERROR_MESSAGE);
        }
        else if(p1 == 3 && p2 == 1)
        {
            p1Health--;
            JOptionPane.showMessageDialog(rootPane,"Player 2 Wins\n Player 1 Health:" + p1Health,"RPS" ,JOptionPane.CLOSED_OPTION);
        }
        else if(p1 == 3 && p2 == 2)
        {
            p2Health--;
            JOptionPane.showMessageDialog(rootPane,"Player 1 Wins\n Player 2 Health:" + p2Health,"RPS" ,JOptionPane.CLOSED_OPTION);
        }
        if(p1Health <= 0)
        {
            JOptionPane.showMessageDialog(rootPane,"Player 1 has no more hearts!\n Player 2 WINS", "Game Over",JOptionPane.INFORMATION_MESSAGE);
        }
        else if(p2Health <= 0)
        {
            JOptionPane.showMessageDialog(rootPane,"Player 2 has no more hearts!\n Player 1 WINS", "Game Over",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRELIM_EXAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRELIM_EXAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRELIM_EXAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRELIM_EXAM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRELIM_EXAM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField p1txt;
    private javax.swing.JTextField p2txt;
    // End of variables declaration//GEN-END:variables
}
